# Generated by Django 5.0.6 on 2024-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_code", models.CharField(max_length=100)),
                ("specialist_code", models.CharField(max_length=100)),
                ("appointment_time", models.DateTimeField()),
                ("status", models.CharField(max_length=50)),
                ("order_id", models.CharField(blank=True, max_length=100, null=True)),
                ("feedback_score", models.IntegerField(blank=True, null=True)),
                ("feedback_text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("patient_name", models.CharField(max_length=100)),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("doctor_name", models.CharField(max_length=100)),
                ("doctor_rating", models.IntegerField(blank=True, null=True)),
                ("doctor_feedback", models.TextField(blank=True, null=True)),
                ("clinic_rating", models.IntegerField(blank=True, null=True)),
                ("clinic_feedback", models.TextField(blank=True, null=True)),
                ("will_return", models.BooleanField(blank=True, null=True)),
                ("audio_link", models.URLField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("order_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("patient_name", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("order_id", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
