# Generated by Django 3.2.25 on 2024-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearchedPatients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_code", models.BigIntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("middlename", models.CharField(blank=True, max_length=100, null=True)),
                ("is_added_in_acs", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
                "db_table": "searched_patient_info",
            },
        ),
    ]
