# Generated by Django 3.2.25 on 2024-08-01 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_savedsearchedpatients"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="SavedSearchedPatients",
        ),
        migrations.RemoveField(
            model_name="review",
            name="appointment_date",
        ),
        migrations.RemoveField(
            model_name="review",
            name="appointment_time",
        ),
        migrations.RemoveField(
            model_name="review",
            name="audio_link",
        ),
        migrations.RemoveField(
            model_name="review",
            name="doctor_name",
        ),
        migrations.RemoveField(
            model_name="review",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="review",
            name="patient_name",
        ),
        migrations.RemoveField(
            model_name="review",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="review",
            name="will_return",
        ),
        migrations.RemoveField(
            model_name="status",
            name="date",
        ),
        migrations.RemoveField(
            model_name="status",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="status",
            name="patient_name",
        ),
        migrations.RemoveField(
            model_name="status",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="review",
            name="RECEPTION_CODE",
            field=models.CharField(default="Unknown", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="review",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
        migrations.AddField(
            model_name="review",
            name="doctor",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="review",
            name="number",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="review",
            name="patient",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="review",
            name="patient_code",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="review",
            name="reception_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="review",
            name="reception_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="review",
            name="will_attend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="status",
            name="RECEPTION_CODE",
            field=models.CharField(default="Unknown", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="status",
            name="call_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="status",
            name="number",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="status",
            name="patient",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="review",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
