# Generated by Django 3.2.25 on 2024-08-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_analysisresult_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysisresult",
            old_name="created_at",
            new_name="analyzed_at",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="analysis_result",
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="clinic_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="clinic_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="doctor_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="doctor_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="will_return",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="reception_code",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
