# Generated by Django 3.2.25 on 2024-08-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20240802_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.AlterField(
            model_name='review',
            name='will_attend',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
