# Generated by Django 3.2.25 on 2024-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20240806_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order_key',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
