# Generated by Django 3.2.25 on 2024-08-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_status_order_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AlterField(
            model_name='review',
            name='RECEPTION_CODE',
            field=models.CharField(default='Unknown', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='RECEPTION_CODE',
            field=models.CharField(default='Unknown', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
