# Generated by Django 3.2.25 on 2024-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20240814_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='audio_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
