# Generated by Django 3.2.25 on 2024-08-20 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_status_audio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('phone', models.CharField(default='Unknown', max_length=255)),
                ('patient', models.CharField(default='Unknown', max_length=255)),
                ('reception_date', models.DateField(default=django.utils.timezone.now)),
                ('reception_time', models.TimeField(default=django.utils.timezone.now)),
                ('doctor', models.CharField(default='Unknown', max_length=255)),
                ('doctor_rating', models.IntegerField(blank=True, null=True)),
                ('doctor_feedback', models.TextField(blank=True, null=True)),
                ('clinic_rating', models.IntegerField(blank=True, null=True)),
                ('clinic_feedback', models.TextField(blank=True, null=True)),
                ('will_attend', models.CharField(blank=True, max_length=10, null=True)),
                ('audio_link', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('RECEPTION_CODE', models.CharField(default='Unknown', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Statuses',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RenameField(
            model_name='statuses',
            old_name='number',
            new_name='phone',
        ),
    ]
