# Generated by Django 3.2.25 on 2024-08-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20240820_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='will_attend',
        ),
    ]
